name: Generate Sitemap
on:
push:
branches: [ main ]
jobs:
generate:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
with:
fetch-depth: 0
- name: Generate Sitemap
uses: cicirello/generate-sitemap@v1
with:
base-url-path: https://grihanicosmetic.com/
